# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint 
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: Clear workspace
      run: |
        rm -rf *
        git reset --hard
        git clean -xdf
    - name: Set PYTHONPATH dynamically for src folders
      run: |
        PYTHONPATH=$(find $(pwd) -type d -name "src" | tr '\n' ':')
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pytest -s --disable-warnings
